# Generated by Django 2.0 on 2018-01-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.IntegerField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=4)),
                ('tel', models.CharField(max_length=16)),
                ('wechat', models.CharField(max_length=16)),
                ('mail', models.CharField(max_length=32)),
                ('qulification', models.CharField(max_length=16)),
                ('work', models.CharField(max_length=64)),
                ('experience', models.CharField(blank=True, max_length=512)),
                ('goal', models.CharField(blank=True, max_length=512)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('attitude', models.CharField(blank=True, max_length=512)),
                ('rate', models.CharField(blank=True, max_length=512)),
                ('suitable', models.CharField(blank=True, max_length=512)),
                ('otherTopic', models.CharField(blank=True, max_length=512)),
                ('communicationType', models.CharField(blank=True, max_length=512)),
                ('advice', models.CharField(blank=True, max_length=512)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
                ('lastName', models.CharField(max_length=16)),
                ('firstName', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=4)),
                ('birthday', models.CharField(max_length=16)),
                ('grade', models.CharField(max_length=8)),
                ('tel', models.CharField(max_length=16)),
                ('wechat', models.CharField(max_length=16)),
                ('headTeacher', models.CharField(max_length=32)),
                ('teacherTel', models.CharField(max_length=16)),
                ('teacherWechat', models.CharField(max_length=16)),
                ('like', models.CharField(max_length=255)),
                ('goodSubjects', models.CharField(max_length=255)),
                ('potentialSubjects', models.CharField(max_length=255)),
                ('interest', models.CharField(max_length=64)),
                ('favor', models.CharField(max_length=64)),
                ('wish', models.CharField(max_length=64)),
                ('school', models.CharField(max_length=64)),
                ('schoolCity', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('providerTel', models.CharField(max_length=16)),
                ('remarks', models.CharField(blank=True, max_length=256)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='selectStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shareRead.Student'),
        ),
    ]
